/* Vector (Lottie) process scenes. The JSON is generated by
   scripts/lottie/build.mjs into public/lottie/<file>.json; the labels below are
   drawn by LottieProcessPlayer on top of the animation, in composition
   coordinates (800×480), so they stay in Hebrew, scale with the canvas, and are
   included in the .webm export.

   TODO (long-term): protein structures already get real 3D via Mol* on the
   protein page; for key processes (e.g. the replisome, the mitotic spindle)
   consider real 3D scenes with Three.js once the 2D versions are reviewed. */

export type SceneLabel = {
  he: string;
  en: string;
  x: number; // label center
  y: number;
  to?: [number, number]; // leader-line target
};

export type LottieScene = {
  file: string;
  frameCount: number; // per step
  width: number;
  height: number;
  // labels per step (index = step)
  labels: SceneLabel[][];
  // always-visible small labels (e.g. strand ends)
  fixed?: SceneLabel[];
  legend?: { he: string; en: string; color: string }[];
  video: { id: string; title: string; source: string };
};

export const LOTTIE_SCENES: Record<string, LottieScene> = {
  mitosis: {
    file: "/lottie/mitosis.json",
    frameCount: 90,
    width: 800,
    height: 480,
    labels: [
      [
        { he: "כרומוזום = 2 כרומטידות אחיות", en: "Chromosome = 2 sister chromatids", x: 590, y: 70, to: [447, 205] },
        { he: "מעטפת הגרעין", en: "Nuclear envelope", x: 250, y: 70, to: [340, 160] },
        { he: "צנטרוזום", en: "Centrosome", x: 110, y: 400, to: [190, 262] },
      ],
      [
        { he: "מעטפת הגרעין מתפרקת", en: "Nuclear envelope breaks down", x: 230, y: 60, to: [300, 150] },
        { he: "קינטוכור", en: "Kinetochore", x: 560, y: 60, to: [433, 228] },
        { he: "מיקרוטובולים של הציר", en: "Spindle microtubules", x: 220, y: 430, to: [290, 262] },
      ],
      [
        { he: "לוח המטאפאזה", en: "Metaphase plate", x: 400, y: 50, to: [400, 125] },
        { he: "קינטוכור", en: "Kinetochore", x: 600, y: 80, to: [413, 168] },
        { he: "קוטב הציר", en: "Spindle pole", x: 680, y: 430, to: [610, 262] },
      ],
      [
        { he: "כרומטידות נמשכות לקטבים", en: "Chromatids pulled to the poles", x: 210, y: 55, to: [210, 190] },
        { he: "מיקרוטובולים פולריים", en: "Polar microtubules", x: 400, y: 440, to: [400, 262] },
      ],
      [
        { he: "חריץ חלוקה (טבעת אקטין-מיוזין)", en: "Cleavage furrow (actin–myosin ring)", x: 400, y: 50, to: [400, 176] },
        { he: "מעטפת גרעין חדשה", en: "New nuclear envelope", x: 190, y: 440, to: [212, 318] },
        { he: "הכרומטין מתרופף", en: "Chromatin decondenses", x: 610, y: 440, to: [590, 270] },
      ],
      [
        { he: "שני תאי בת זהים גנטית", en: "Two genetically identical daughter cells", x: 400, y: 50 },
        { he: "תא בת", en: "Daughter cell", x: 205, y: 440, to: [205, 395] },
        { he: "תא בת", en: "Daughter cell", x: 595, y: 440, to: [595, 395] },
      ],
    ],
    legend: [
      { he: "כרומוזום מהאם", en: "Maternal chromosome", color: "#dc2626" },
      { he: "כרומוזום מהאב", en: "Paternal chromosome", color: "#2563eb" },
    ],
    video: { id: "IvJrDsRuWxQ", title: "Kinetochore and Mitosis — Drew Berry", source: "WEHI" },
  },

  "dna-replication": {
    file: "/lottie/dna-replication.json",
    frameCount: 90,
    width: 800,
    height: 480,
    labels: [
      [
        { he: "הליקאז (מזלג השכפול)", en: "Helicase (replication fork)", x: 430, y: 60, to: [434, 222] },
        { he: "טופואיזומראז", en: "Topoisomerase", x: 650, y: 120, to: [550, 228] },
        { he: "חלבוני SSB", en: "SSB proteins", x: 300, y: 430, to: [398, 300] },
      ],
      [
        { he: "פריימר RNA", en: "RNA primer", x: 170, y: 250, to: [262, 176] },
        { he: "פריימאז", en: "Primase", x: 330, y: 430, to: [340, 318] },
      ],
      [
        { he: "DNA פולימראז III", en: "DNA polymerase III", x: 470, y: 60, to: [464, 160] },
        { he: "גדיל מוביל — רציף", en: "Leading strand — continuous", x: 250, y: 250, to: [380, 176] },
      ],
      [
        { he: "מקטעי אוקזאקי", en: "Okazaki fragments", x: 470, y: 430, to: [420, 332] },
        { he: "גדיל מפגר", en: "Lagging strand", x: 170, y: 430, to: [260, 332] },
        { he: "המזלג מתקדם", en: "Fork moves on", x: 690, y: 140, to: [644, 236] },
      ],
      [
        { he: "DNA פולימראז I מחליף פריימרים", en: "DNA pol I replaces primers", x: 360, y: 430, to: [330, 312] },
      ],
      [
        { he: "DNA ליגאז סוגר את החריצים", en: "DNA ligase seals the nicks", x: 420, y: 430, to: [410, 318] },
        { he: "כל מולקולה: גדיל ישן + גדיל חדש", en: "Each molecule: one old + one new strand", x: 330, y: 60 },
      ],
    ],
    fixed: [
      { he: "3'", en: "3'", x: 24, y: 128 },
      { he: "5'", en: "5'", x: 24, y: 372 },
      { he: "5'", en: "5'", x: 780, y: 214 },
      { he: "3'", en: "3'", x: 780, y: 286 },
    ],
    legend: [
      { he: "גדיל תבנית (ישן)", en: "Template (old) strand", color: "#1e3a8a" },
      { he: "DNA חדש", en: "New DNA", color: "#16a34a" },
      { he: "פריימר RNA", en: "RNA primer", color: "#f97316" },
    ],
    video: { id: "TNKWgcFPHqw", title: "DNA replication - 3D", source: "yourgenome (Wellcome Genome Campus)" },
  },
};
