// Hebrew for the English labels embedded in step-animation svgData (ProcessStep).
// Used by ProcessAnimation / ProcessInlineVideo when lang === "he". Labels not
// listed here (symbols, formulas, new AI output) are shown as-is.
// LRI…PDI isolates keep formulas like 5'→3' readable inside RTL text.
const LRI = String.fromCharCode(0x2066), PDI = String.fromCharCode(0x2069);
const ltr = (s: string) => `${LRI}${s}${PDI}`;

export const SVG_LABELS_HE: Record<string, string> = {
  "Crossing Over → genetic recombination": "שחלוף ← רקומבינציה גנטית",
  "Synapsis (bivalent formation)": "סינפסיס (היווצרות ביוולנט)",
  "n (haploid)": "n (הפלואידי)",
  "Homologs separate → Reduction division": "ההומולוגים נפרדים ← חלוקת הפחתה",
  "4 haploid gametes": "4 גמטות הפלואידיות",
  "(each genetically unique)": "(כל אחת ייחודית גנטית)",
  "🌡️ 95°C — HEAT": `🌡️ ${ltr("95°C")} — דנטורציה`,
  "Single-stranded templates": "תבניות חד-גדיליות",
  "H-bonds broken ✕": "קשרי המימן נשברים ✕",
  "🌡️ 58°C — ANNEALING": `🌡️ ${ltr("58°C")} — הצמדת פריימרים`,
  "Forward primer →": "→ פריימר קדמי",
  "← Reverse primer": "← פריימר אחורי",
  "Primers flank the target region": "הפריימרים תוחמים את אזור המטרה",
  "🌡️ 72°C — EXTENSION": `🌡️ ${ltr("72°C")} — הארכה`,
  "Taq Polymerase extends 5'→3'": `Taq פולימראז מאריך ${ltr("5'→3'")}`,
  "Cycle 1→2→4→8…→2ⁿ copies": `עותקים: ${ltr("1→2→4→8…→2ⁿ")}`,
  "PFK-1 (rate-limiting)": "PFK-1 (שלב מגביל קצב)",
  "Investment: -2 ATP": `השקעה: ${ltr("−2 ATP")}`,
  "↓ Aldolase": "↓ אלדולאז",
  "→ isomerase →": "איזומראז",
  "2 molecules → payoff phase": "2 מולקולות ← שלב הרווח",
  "5 rxns": "5 תגובות",
  "Net gain: 2 ATP + 2 NADH": `רווח נקי: ${ltr("2 ATP + 2 NADH")}`,
  "(4 produced − 2 invested)": "(4 נוצרו − 2 הושקעו)",
  "mRNA 5'→3'": ltr("mRNA 5'→3'"),
  "AUG (start)": "AUG (קודון התחלה)",
  "40S small subunit": "תת-יחידה קטנה 40S",
  "← scanning for AUG": "← סריקה לאיתור AUG",
  "60S large subunit": "תת-יחידה גדולה 60S",
  "P site (Met-tRNA)": "אתר P (Met-tRNA)",
  "A site (empty)": "אתר A (ריק)",
  "Growing peptide chain": "שרשרת פפטיד מתארכת",
  "new tRNA": "tRNA חדש",
  "Peptide bond": "קשר פפטידי",
  "→→→ translocation": "טרנסלוקציה",
  "STOP (UAA)": "קודון סיום (UAA)",
  "Released polypeptide → folds!": "הפוליפפטיד משתחרר ומתקפל",
  "Ribosome dissociates → reused": "הריבוזום מתפרק ומשמש שוב",
  "Cytoplasm": "ציטופלזמה",
  "Glucose": "גלוקוז",
  "10 steps": "10 שלבים",
  "2 Pyruvate": "2 פירובט",
  "Net: 2 ATP + 2 NADH": `נטו: ${ltr("2 ATP + 2 NADH")}`,
  "Mitochondrial Matrix": "מטריצת המיטוכונדריה",
  "Pyruvate": "פירובט",
  "CO₂ released": "שחרור CO₂",
  "Acetyl-CoA →": "Acetyl-CoA",
  "Inner Mitochondrial Membrane": "הממברנה הפנימית של המיטוכונדריה",
  "H⁺ gradient →→→": "מפל ריכוזים של H⁺",
  "~30 ATP": ltr("~30 ATP"),
  "Cell": "תא",
  "Plasma Membrane": "קרום התא",
  "Peptidoglycan": "פפטידוגליקן",
  "Lag Phase": "שלב ההשהיה",
  "Log Phase": "שלב הגדילה המעריכית",
  "Lag": "השהיה",
  "Log": "גדילה מעריכית",
  "Stationary": "התייצבות",
  "Chromosome 1": "כרומוזום 1",
  "Chromosome 2": "כרומוזום 2",
  "Genotype": "גנוטיפ",
  "Phenotype": "פנוטיפ",
  "Gene 1": "גן 1",
  "Mitochondria": "מיטוכונדריה",
  "Nucleus": "גרעין",
  "Nuclear DNA": "DNA גרעיני",
  "Mother": "אם",
  "Child": "צאצא",
  "Cellular process": "תהליך תאי",
  "Mitochondrial traits": "תכונות מיטוכונדריאליות",
  "Nuclear traits": "תכונות גרעיניות",
  "binding": "קישור",
  "complex": "קומפלקס",
  "Heart": "לב",
  "Lung": "ריאות",
  "Body": "רקמות הגוף",
  "Blood": "דם",
  "Oxygenated Blood": "דם מחומצן",
  "Riboswitch structure": "מבנה הריבוסוויץ'",
  "Metabolite binds RNA": "מטבוליט נקשר ל-RNA",
  "RNA structure change": "שינוי במבנה ה-RNA",
  "Gene expression": "ביטוי גנים",
  "Applications": "יישומים",
  "Riboswitches summary": "סיכום",
  "Target protein": "חלבון מטרה",
  "Ubiquitin": "אוביקוויטין",
  "E3 ligase": "E3 ליגאז",
  "Poly-ubiquitin chain": "שרשרת פולי-אוביקוויטין",
  "26S proteasome": "פרוטאזום 26S",
  "Recycled Ub": "Ub ממוחזר",
  "Deubiquitination + unfolding": "הסרת אוביקוויטין ופרישה",
  "Short peptides": "פפטידים קצרים",
  "Recycled ubiquitin": "אוביקוויטין ממוחזר",
};

export function svgLabel(label: string, lang: string) {
  return lang === "he" ? SVG_LABELS_HE[label] ?? label : label;
}

// viewBox is 400 wide; on a ~360px phone this keeps labels ≥ ~12.5 CSS px.
export const MIN_SVG_LABEL_SIZE = 14;
